set -g base-index 1
setw -g pane-base-index 1

set-option -g history-limit 100000

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

set -ga terminal-features "*:hyperlinks"

set -g set-clipboard on

unbind C-b
set -g prefix C-k
bind C-k send-prefix

setw -g mode-keys vi

bind -n M-v copy-mode
bind v copy-mode

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi Enter send-keys -X cancel

if-shell 'uname | grep -q Darwin' \
  "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy' ; bind-key -nr C-y run 'tmux show-buffer | pbcopy'" \
  "bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard' ; bind-key -nr C-y run 'tmux show-buffer | xclip -selection clipboard'"

set -sg escape-time 10

set -g set-titles on
set -g set-titles-string "#T"

set -g mouse on

set-option -g focus-events on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H previous-window
bind -r L next-window

bind -n M-h previous-window
bind -n M-l next-window

bind w choose-tree -Zw -F '#{?pane_format,#{pane_current_command}#{?pane_active,*,}#{?#{&&:#{pane_title},#{!=:#{pane_title},#{host}}},: "#{pane_title}",},#{?window_format,#{window_name}#{window_flags}#{?#{&&:#{==:#{window_panes},1},#{&&:#{pane_title},#{!=:#{pane_title},#{host}}}},: "#{pane_title}",},#{session_windows} windows#{?session_attached, (attached),}}}'

set -g status-position bottom
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100

set-option -g status-style "fg=#bdae93,bg=#1d2021"

set -g status-left "#[fg=#1d2021,bg=#fabd2f,bold]  avhi #[fg=#fabd2f,bg=#1d2021,nobold] "

set -g status-right "#[fg=#3c3836,bg=#1d2021]#[fg=#bdae93,bg=#3c3836] 󰋊 #(df -H / | awk 'NR==2 {print $4\" / \"$2}') #[fg=#fabd2f,bg=#3c3836]#[fg=#1d2021,bg=#fabd2f,bold] %H:%M "
set -g status-interval 2

set-window-option -g window-status-style "fg=#bdae93,bg=#1d2021"
set-window-option -g window-status-format "#[fg=#1d2021,bg=#3c3836]#[fg=#bdae93,bg=#3c3836] #I:#W #[fg=#3c3836,bg=#1d2021]"

set-window-option -g window-status-current-style "fg=#fabd2f,bg=#504945"
set-window-option -g window-status-current-format "#[fg=#1d2021,bg=#504945]#[fg=#fabd2f,bg=#504945,bold] #I:#W #[fg=#504945,bg=#1d2021]"

set -g window-status-separator ""

set-option -g pane-border-style "fg=#3c3836"
set-option -g pane-active-border-style "fg=#504945"

set-option -g message-style "fg=#d5c4a1,bg=#3c3836"

set-option -g display-panes-active-colour "#b8bb26"
set-option -g display-panes-colour "#fabd2f"

set-window-option -g clock-mode-colour "#b8bb26"

set-window-option -g mode-style "fg=#bdae93,bg=#504945"

set-window-option -g window-status-bell-style "fg=#3c3836,bg=#fb4934"

bind-key "K" run-shell "sesh connect \"$(sesh list | fzf-tmux -p 55%,60% --no-sort --ansi --border-label ' sesh ')\""

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'sainnhe/tmux-fzf'

if-shell "uname | grep -q Linux" "source-file ~/.config/tmux/linux.conf"

if-shell "test -d ~/.tmux/plugins/tpm" "run '~/.tmux/plugins/tpm/tpm'"
